"""Over-the-air firmware updater.

Flow
----
1. `check_for_update()` GETs `latest.json` from the release server. The
   manifest carries `version`, `bundle_url`, `sha256`, `signature` (Ed25519
   over the sha256 hex digest), and `min_hardware_version`.
2. If the advertised version > current __version__, `apply_update()`
   downloads the bundle into `staging/<version>/`, verifies sha256 +
   signature, then runs `_self_test()` (an `import` smoke check on every
   module).
3. On pass — atomically swap symlink `current/` to point at the new
   directory and SIGTERM ourselves; systemd's Restart=always picks us
   back up running the new code.
4. On fail — leave staging in place for forensics, restore the old
   `current/` symlink (no-op if we never swapped), publish a
   `firmware_update_failed` event so the admin UI surfaces it.

The signing keypair is generated by `firmware/tools/build.sh`. The
public half is hard-coded below — rotating it requires a manual firmware
push followed by a re-sign on the new key. We accept that overhead
because the alternative (fetching the pubkey over the wire) defeats the
whole point of signing.

Triggering: invoked synchronously from `command_handler._cmd_update_firmware`,
or scheduled by a daily cron (`firmware/tools/ota-cron.sh`, optional —
not shipped here, just a hook). Never run two updates concurrently —
`_lock` enforces that within the process; cron should also use flock.
"""
from __future__ import annotations

import hashlib
import json
import logging
import os
import shutil
import signal
import subprocess
import sys
import tarfile
import tempfile
import threading
import time
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Optional

from . import __version__

log = logging.getLogger(__name__)

# Hard-coded Ed25519 release-signing public key (raw 32 bytes hex).
# Rotated by physically re-flashing the gateway — there is no in-band
# rotation path on purpose. See docs/security.md.
RELEASE_PUBKEY_HEX = (
    # Placeholder until the first build; replace at provisioning time.
    "0000000000000000000000000000000000000000000000000000000000000000"
)

DEFAULT_MANIFEST_URL = "https://releases.tspowergrid.com/firmware/latest.json"

# Filesystem layout (production):
#   /opt/ts-gateway/current        symlink -> versions/<vX.Y.Z>/
#   /opt/ts-gateway/versions/...   immutable per-release dirs
#   /opt/ts-gateway/staging/...    in-flight downloads (cleaned on success)
INSTALL_ROOT = Path(os.environ.get("TS_GATEWAY_ROOT", "/opt/ts-gateway"))


@dataclass
class UpdateManifest:
    version: str
    bundle_url: str
    sha256: str
    signature: str  # hex Ed25519 over the sha256 hex string (ascii)
    min_hardware_version: str = "1.0"
    notes: str = ""


class OtaError(RuntimeError):
    """Raised when an update is rejected — caller catches and acks."""


_lock = threading.Lock()


# ---------------------------------------------------------------------------
# Public entry points
# ---------------------------------------------------------------------------
def check_for_update(
    manifest_url: str = DEFAULT_MANIFEST_URL,
    timeout: float = 10.0,
) -> Optional[UpdateManifest]:
    """Fetch latest.json. Returns None when we're already current."""
    try:
        with urllib.request.urlopen(manifest_url, timeout=timeout) as resp:
            raw = json.loads(resp.read().decode("utf-8"))
    except (OSError, ValueError) as exc:
        log.warning("manifest fetch failed: %s", exc)
        return None

    manifest = UpdateManifest(
        version=str(raw["version"]),
        bundle_url=str(raw["bundle_url"]),
        sha256=str(raw["sha256"]).lower(),
        signature=str(raw["signature"]).lower(),
        min_hardware_version=str(raw.get("min_hardware_version", "1.0")),
        notes=str(raw.get("notes", "")),
    )
    if _version_tuple(manifest.version) <= _version_tuple(__version__):
        log.info("already on %s — manifest offers %s", __version__, manifest.version)
        return None
    return manifest


def apply_update(
    manifest: UpdateManifest,
    publish_event: Optional[Callable[[dict], bool]] = None,
    install_root: Path = INSTALL_ROOT,
) -> dict:
    """Download → verify → self-test → swap → restart.

    Returns a small dict with the outcome that's safe to embed in a
    `command_ack`. Raises `OtaError` on any failure; the caller should
    publish a `firmware_update_failed` event with the reason.
    """
    if not _lock.acquire(blocking=False):
        raise OtaError("update_already_in_progress")
    try:
        log.info("applying update %s -> %s", __version__, manifest.version)
        staging = install_root / "staging" / manifest.version
        staging.mkdir(parents=True, exist_ok=True)
        bundle_path = staging / "bundle.tar.gz"

        _download(manifest.bundle_url, bundle_path)
        _verify_hash(bundle_path, manifest.sha256)
        _verify_signature(manifest.sha256, manifest.signature)

        target_dir = install_root / "versions" / manifest.version
        if target_dir.exists():
            shutil.rmtree(target_dir)
        target_dir.mkdir(parents=True)
        _extract(bundle_path, target_dir)

        _self_test(target_dir)

        _swap_current(install_root, target_dir)

        # Clean staging — bundle is no longer needed.
        shutil.rmtree(staging, ignore_errors=True)

        if publish_event is not None:
            publish_event({
                "event": "firmware_update_succeeded",
                "from_version": __version__,
                "to_version": manifest.version,
                "timestamp": _iso_now(),
            })

        log.info("update staged successfully — sending SIGTERM for systemd to restart us")
        # Schedule the restart slightly after returning so the caller's
        # ack publish has a chance to flush over MQTT first.
        _schedule_self_restart(delay_sec=2.0)
        return {"applied": True, "version": manifest.version}
    except OtaError:
        raise
    except Exception as exc:
        log.exception("ota failed")
        if publish_event is not None:
            publish_event({
                "event": "firmware_update_failed",
                "version": manifest.version,
                "reason": str(exc),
                "timestamp": _iso_now(),
            })
        raise OtaError(str(exc)) from exc
    finally:
        _lock.release()


# ---------------------------------------------------------------------------
# Internals
# ---------------------------------------------------------------------------
def _download(url: str, dest: Path, timeout: float = 60.0) -> None:
    log.info("downloading %s -> %s", url, dest)
    with urllib.request.urlopen(url, timeout=timeout) as resp, open(dest, "wb") as fh:
        shutil.copyfileobj(resp, fh, length=64 * 1024)


def _verify_hash(path: Path, expected_hex: str) -> None:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            h.update(chunk)
    actual = h.hexdigest()
    if actual != expected_hex.lower():
        raise OtaError(f"sha256_mismatch expected={expected_hex} actual={actual}")
    log.info("sha256 ok (%s…)", actual[:12])


def _verify_signature(sha256_hex: str, signature_hex: str) -> None:
    """Verify the manifest signature over the bundle's sha256 hex digest.

    Signing the digest (instead of the whole bundle) keeps the build
    pipeline simple — `firmware/tools/build.sh` runs `openssl dgst` for
    the hash and `python -m firmware.tools.sign` for the Ed25519 sig.
    """
    try:
        from cryptography.hazmat.primitives.asymmetric.ed25519 import (
            Ed25519PublicKey,
        )
        from cryptography.exceptions import InvalidSignature
    except ImportError as exc:
        raise OtaError("cryptography_not_installed") from exc

    if RELEASE_PUBKEY_HEX == "0" * 64:
        raise OtaError("release_pubkey_unset")

    try:
        pub = Ed25519PublicKey.from_public_bytes(bytes.fromhex(RELEASE_PUBKEY_HEX))
        pub.verify(bytes.fromhex(signature_hex), sha256_hex.encode("ascii"))
    except (ValueError, InvalidSignature) as exc:
        raise OtaError(f"signature_invalid: {exc}") from exc
    log.info("signature ok")


def _extract(bundle_path: Path, dest: Path) -> None:
    """Extract with a path-traversal guard. Tarballs from a trusted
    signer should never escape `dest`, but defence-in-depth is cheap."""
    log.info("extracting bundle into %s", dest)
    with tarfile.open(bundle_path, "r:gz") as tf:
        members = tf.getmembers()
        for m in members:
            target = (dest / m.name).resolve()
            if not str(target).startswith(str(dest.resolve())):
                raise OtaError(f"tar_traversal: {m.name}")
        tf.extractall(dest)


def _self_test(version_dir: Path) -> None:
    """Spawn a fresh Python that imports every shipped module. If any of
    them throws (syntax error, missing dep, broken pickled state), abort
    the swap before we point `current/` at it.

    We do this in a subprocess so a half-loaded module can't poison the
    running interpreter."""
    log.info("self-test: importing extracted modules")
    cmd = [
        sys.executable,
        "-c",
        # Important: use the package layout the bundle is built with —
        # `ts_gateway` package at the root of the extracted dir.
        (
            "import sys, importlib, pkgutil; "
            f"sys.path.insert(0, {str(version_dir)!r}); "
            "pkg = importlib.import_module('ts_gateway'); "
            "[importlib.import_module(f'ts_gateway.{m.name}') "
            " for m in pkgutil.iter_modules(pkg.__path__) if not m.ispkg]"
        ),
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
    if proc.returncode != 0:
        raise OtaError(
            f"self_test_failed rc={proc.returncode} stderr={proc.stderr.strip()[:400]}"
        )
    log.info("self-test passed")


def _swap_current(install_root: Path, target: Path) -> None:
    """Atomically point `<root>/current` at the new version dir.

    Uses rename-over-symlink so a concurrent reader either sees the old
    target or the new one, never a half-state.
    """
    current = install_root / "current"
    tmp = install_root / f".current.{os.getpid()}"
    if tmp.exists() or tmp.is_symlink():
        tmp.unlink()
    tmp.symlink_to(target, target_is_directory=True)
    os.replace(tmp, current)  # atomic on POSIX
    log.info("symlink %s -> %s", current, target)


def _schedule_self_restart(delay_sec: float) -> None:
    """SIGTERM ourselves after a short grace period. systemd's
    Restart=always brings us back running the new symlink target."""
    def _bomb() -> None:
        time.sleep(delay_sec)
        os.kill(os.getpid(), signal.SIGTERM)

    threading.Thread(target=_bomb, daemon=True, name="ota-restart").start()


def _version_tuple(v: str) -> tuple[int, ...]:
    """Best-effort semver parse — `0.1.0` -> (0,1,0). Non-numeric
    components are ignored so we never compare strings."""
    parts = []
    for chunk in v.split("."):
        try:
            parts.append(int(chunk.split("-")[0]))
        except ValueError:
            parts.append(0)
    return tuple(parts)


def _iso_now() -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
