#!/usr/bin/env bash
# provision.sh — turn a fresh Pi into a registered T&S gateway.
#
# Run on the operator's workstation (which holds the CA private key),
# NOT on the gateway itself. Outputs go into a single directory the
# operator then sneaker-nets onto the Pi (or pushes via SSH).
#
# What you get per run:
#   out/<site_id>/
#     ca.crt              copy of the issuing CA certificate
#     client.crt          gateway's signed client cert (CN = site_id)
#     client.key          gateway's private key (chmod 600)
#     config.yaml         pre-filled config — site_id, MQTT host, cert paths
#     pairing.png         QR code: gateway serial + 1-time pairing token
#     pairing.json        same payload as the QR, for backend ingestion
#     INSTALL.md          one-page operator runbook
#
# Usage:
#   ./provision.sh \
#       --site-id 7c9e6679-7425-40de-944b-e07fc1f90ae7 \
#       --serial  TSGW-2026-0001 \
#       --mqtt-host mqtt.tspowergrid.com
#
# CA assumed at infra/mqtt/certs/ca.{crt,key} — see infra/mqtt/revocation.py
# for the same on-disk layout.

set -euo pipefail

SITE_ID=""
SERIAL=""
MQTT_HOST="mqtt.tspowergrid.com"
MQTT_PORT="8883"
OUT_BASE=""

usage() {
    sed -n '/^# /,/^set/p' "$0" | sed 's/^# \{0,1\}//' | sed '$d'
    exit 1
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --site-id)    SITE_ID="$2"; shift 2;;
        --serial)     SERIAL="$2"; shift 2;;
        --mqtt-host)  MQTT_HOST="$2"; shift 2;;
        --mqtt-port)  MQTT_PORT="$2"; shift 2;;
        --out)        OUT_BASE="$2"; shift 2;;
        -h|--help)    usage;;
        *)            echo "unknown arg: $1" >&2; usage;;
    esac
done

if [[ -z "${SITE_ID}" || -z "${SERIAL}" ]]; then
    echo "missing --site-id or --serial" >&2
    usage
fi

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${HERE}/../.." && pwd)"
CA_DIR="${REPO_ROOT}/infra/mqtt/certs"
CA_CRT="${CA_DIR}/ca.crt"
CA_KEY="${CA_DIR}/ca.key"
ISSUED_DIR="${CA_DIR}/issued"

if [[ ! -f "${CA_CRT}" || ! -f "${CA_KEY}" ]]; then
    echo "CA material missing at ${CA_DIR} — bootstrap the CA first." >&2
    exit 1
fi

OUT_BASE="${OUT_BASE:-${HERE}/out}"
OUT_DIR="${OUT_BASE}/${SITE_ID}"
mkdir -p "${OUT_DIR}" "${ISSUED_DIR}"
chmod 700 "${OUT_DIR}"

echo "==> generating client key + CSR (CN=${SITE_ID})"
CLIENT_KEY="${OUT_DIR}/client.key"
CLIENT_CSR="${OUT_DIR}/client.csr"
CLIENT_CRT="${OUT_DIR}/client.crt"
openssl req -new -newkey ec -pkeyopt ec_paramgen_curve:P-256 -nodes \
    -keyout "${CLIENT_KEY}" \
    -out "${CLIENT_CSR}" \
    -subj "/CN=${SITE_ID}" >/dev/null 2>&1
chmod 600 "${CLIENT_KEY}"

echo "==> signing CSR with CA (1y validity)"
# x509 extensions — keyUsage + extendedKeyUsage so EMQX is happy.
EXT_FILE="$(mktemp)"
trap 'rm -f "${EXT_FILE}"' EXIT
cat > "${EXT_FILE}" <<EOF
basicConstraints = CA:FALSE
keyUsage = critical, digitalSignature, keyEncipherment
extendedKeyUsage = clientAuth
subjectAltName = DNS:${SITE_ID}
EOF

# Bump the CA's serial register up by one; OpenSSL needs a serial source.
SERIAL_FILE="${CA_DIR}/serial"
[[ -f "${SERIAL_FILE}" ]] || echo "1000" > "${SERIAL_FILE}"

openssl x509 -req \
    -in "${CLIENT_CSR}" \
    -CA "${CA_CRT}" -CAkey "${CA_KEY}" \
    -CAserial "${SERIAL_FILE}" \
    -days 365 -sha256 \
    -extfile "${EXT_FILE}" \
    -out "${CLIENT_CRT}" >/dev/null 2>&1
rm -f "${CLIENT_CSR}"

# Stash a copy under issued/<serial>.crt so revocation.py can find it.
ISSUED_SERIAL="$(openssl x509 -in "${CLIENT_CRT}" -noout -serial | cut -d= -f2)"
cp "${CLIENT_CRT}" "${ISSUED_DIR}/${ISSUED_SERIAL}.crt"
echo "    serial ${ISSUED_SERIAL}"

cp "${CA_CRT}" "${OUT_DIR}/ca.crt"

echo "==> writing config.yaml"
cat > "${OUT_DIR}/config.yaml" <<EOF
# Generated by provision.sh — do NOT commit. Move to /etc/ts-gateway/.
site_id: "${SITE_ID}"

mqtt:
  host: "${MQTT_HOST}"
  port: ${MQTT_PORT}
  ca_cert: "/etc/ts-gateway/certs/ca.crt"
  client_cert: "/etc/ts-gateway/certs/client.crt"
  client_key: "/etc/ts-gateway/certs/client.key"
  keepalive_sec: 60
  will_topic_suffix: "gateway/heartbeat"

intervals:
  meter_poll_sec: 30
  meter_stagger_sec: 2
  heartbeat_sec: 300
  health_alert_sec: 60

offline_queue:
  db_path: "/var/lib/ts-gateway/queue.db"
  max_age_hours: 72
  drain_batch: 100

modbus:
  port: "/dev/ttyUSB0"
  baudrate: 9600
  parity: "N"
  stopbits: 1
  bytesize: 8
  timeout_sec: 2

# Roster — populate with the meter UUIDs registered in Supabase for this site.
meters: []

thresholds:
  cpu_temp_c: 80
  disk_used_pct: 90
  mem_used_pct: 90

logging:
  level: "INFO"
EOF
chmod 640 "${OUT_DIR}/config.yaml"

echo "==> generating pairing token + QR"
# 32 url-safe random bytes ~= 256 bits of entropy. The backend stores
# the token's sha256, not the raw token, so we don't have a recoverable
# secret on the server.
PAIR_TOKEN="$(python3 -c 'import secrets; print(secrets.token_urlsafe(32))')"
TOKEN_HASH="$(printf "%s" "${PAIR_TOKEN}" | shasum -a 256 | awk '{print $1}')"

PAYLOAD_JSON="${OUT_DIR}/pairing.json"
QR_PNG="${OUT_DIR}/pairing.png"
cat > "${PAYLOAD_JSON}" <<EOF
{
  "v": 1,
  "site_id": "${SITE_ID}",
  "serial": "${SERIAL}",
  "pairing_token": "${PAIR_TOKEN}",
  "pairing_token_sha256": "${TOKEN_HASH}",
  "mqtt_host": "${MQTT_HOST}",
  "issued_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
}
EOF
chmod 600 "${PAYLOAD_JSON}"

# Build the QR. We embed only the small payload (serial + token + site
# id) — the cert material is too big for a QR and goes via the file
# bundle instead.
python3 - "${OUT_DIR}/pairing.png" "${SERIAL}" "${SITE_ID}" "${PAIR_TOKEN}" <<'PY'
import sys
try:
    import qrcode
except ImportError:
    sys.exit(
        "qrcode not installed — `pip install qrcode[pil]` on the operator workstation"
    )
out_path, serial, site_id, token = sys.argv[1:5]
data = f"tspg://pair?serial={serial}&site={site_id}&token={token}"
img = qrcode.make(data)
img.save(out_path)
print(f"    qr -> {out_path}  ({data[:60]}…)")
PY

echo "==> writing INSTALL.md"
cat > "${OUT_DIR}/INSTALL.md" <<EOF
# Gateway provisioning bundle — ${SERIAL}

Site: \`${SITE_ID}\`
MQTT: \`${MQTT_HOST}:${MQTT_PORT}\`
Cert serial: \`${ISSUED_SERIAL}\`
Cert expires: $(openssl x509 -in "${CLIENT_CRT}" -noout -enddate | cut -d= -f2)

## On the Pi

\`\`\`bash
# 1. drop in cert + config (run as root)
sudo install -d -m 700 /etc/ts-gateway/certs
sudo install -m 644 ca.crt        /etc/ts-gateway/certs/ca.crt
sudo install -m 644 client.crt    /etc/ts-gateway/certs/client.crt
sudo install -m 600 client.key    /etc/ts-gateway/certs/client.key
sudo install -m 640 config.yaml   /etc/ts-gateway/config.yaml

# 2. install + start the firmware
cd ts-power-grid/firmware/ts_gateway
sudo bash install.sh
sudo systemctl start ts-gateway
journalctl -u ts-gateway -f
\`\`\`

## Pairing

Scan \`pairing.png\` from the admin app to register the gateway in
Supabase. The pairing token is one-time — once consumed the backend
will refuse a second use.

## Custody

\`pairing.json\` and \`client.key\` are secrets — wipe this directory
once the Pi is online and confirmed in the admin fleet view.
EOF

echo
echo "Bundle ready:  ${OUT_DIR}/"
ls -la "${OUT_DIR}/"
